"""Differentiable many-body completion simulation and data utilities."""

from .ablation import (
    AblationMode,
    AblationSpec,
    CompletionStage,
    get_ablation_spec,
)
from .composition import (
    CompletionOptions,
    PhysicalParameters,
    periodic_correction_mse,
    run_local_completion,
    scalar_generator,
)
from .energies import EnergyParameters, total_energy
from .generator import (
    EquivariantGeneratorConfig,
    apply_equivariant_displacement_field,
    apply_equivariant_generator,
    count_generator_parameters,
    flatten_generator_parameters,
    initialize_equivariant_generator,
    make_periodic_grid_anchors,
    restore_generator_parameters,
)
from .generator_training import (
    GENERATOR_METRIC_NAMES,
    AdamOptions,
    GeneratorBatch,
    GeneratorObjectiveWeights,
    GeneratorTrainingResult,
    ablation_generator_objective,
    ablation_training_objective,
    evaluate_generator_completion,
    generate_batch_coordinates,
    local_generator_objective,
    parameter_directional_derivative_sweep,
    train_equivariant_generator,
)
from .geometry import (
    chord_displacements,
    chord_distances,
    minimum_image_displacement,
    periodic_direction_displacements,
    translation_gauge_fixed_displacement,
    wrap_positions,
)
from .flow_matching import (
    ConditionalFlowConfig,
    FlowSamplingOptions,
    apply_conditional_velocity,
    conditional_flow_matching_loss,
    flow_matching_path,
    initialize_conditional_flow,
    sample_conditional_flow,
)
from .flow_training import (
    FlowAdamOptions,
    FlowTrainingBatch,
    FlowTrainingResult,
    sample_flow_conditions_chunked,
    train_conditional_flow,
)
from .homometric import (
    HomometricDatasetConfig,
    are_torus_d4_congruent,
    base_homometric_coordinates,
    classify_homometric_configurations,
    generate_homometric_dataset,
    homometric_mode_metrics,
    validate_homometric_dataset,
)
from .observables import PairBasis, ensemble_pair_moments
from .projection import ProjectionOptions, project_ensemble_moments
from .relaxation import RelaxationOptions, relax_proximal
from .scalar_training import (
    ScalarGeneratorProblem,
    ScalarObjectiveWeights,
    ScalarTrainingOptions,
    local_s3_objective,
    scalar_gradient_sweep,
    train_scalar_parameter,
)
from .simulators import LangevinConfig, simulate_overdamped_langevin

__all__ = [
    "AblationMode",
    "AblationSpec",
    "AdamOptions",
    "ConditionalFlowConfig",
    "EquivariantGeneratorConfig",
    "FlowAdamOptions",
    "FlowSamplingOptions",
    "FlowTrainingBatch",
    "FlowTrainingResult",
    "GeneratorBatch",
    "GeneratorObjectiveWeights",
    "GeneratorTrainingResult",
    "HomometricDatasetConfig",
    "GENERATOR_METRIC_NAMES",
    "CompletionOptions",
    "CompletionStage",
    "EnergyParameters",
    "LangevinConfig",
    "PhysicalParameters",
    "PairBasis",
    "ProjectionOptions",
    "RelaxationOptions",
    "ScalarGeneratorProblem",
    "ScalarObjectiveWeights",
    "ScalarTrainingOptions",
    "chord_displacements",
    "chord_distances",
    "classify_homometric_configurations",
    "minimum_image_displacement",
    "ablation_generator_objective",
    "ablation_training_objective",
    "are_torus_d4_congruent",
    "base_homometric_coordinates",
    "ensemble_pair_moments",
    "evaluate_generator_completion",
    "generate_batch_coordinates",
    "generate_homometric_dataset",
    "get_ablation_spec",
    "homometric_mode_metrics",
    "local_s3_objective",
    "periodic_correction_mse",
    "periodic_direction_displacements",
    "translation_gauge_fixed_displacement",
    "project_ensemble_moments",
    "run_local_completion",
    "relax_proximal",
    "scalar_generator",
    "scalar_gradient_sweep",
    "simulate_overdamped_langevin",
    "train_scalar_parameter",
    "total_energy",
    "apply_conditional_velocity",
    "apply_equivariant_displacement_field",
    "apply_equivariant_generator",
    "conditional_flow_matching_loss",
    "flow_matching_path",
    "initialize_conditional_flow",
    "sample_conditional_flow",
    "sample_flow_conditions_chunked",
    "count_generator_parameters",
    "flatten_generator_parameters",
    "initialize_equivariant_generator",
    "local_generator_objective",
    "make_periodic_grid_anchors",
    "restore_generator_parameters",
    "parameter_directional_derivative_sweep",
    "train_conditional_flow",
    "train_equivariant_generator",
    "validate_homometric_dataset",
    "wrap_positions",
]
